import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CssBaseline } from '@mui/material'
import theme from '../theme.js'

import { Experimental_CssVarsProvider as CssVarsProvider } from '@mui/material/styles'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <CssBaseline />
      <body className={inter.className}>
        <CssVarsProvider theme={theme}>
          <Header />
          <main>{children}</main>
          <footer>footer</footer>
        </CssVarsProvider>
      </body>
    </html>
  )
}
